### ISSUE TITLE
Incoherent simfile's #MUSIC behavior

### ISSUE THREAD

**Issue by florczakraf** [telperion/nine-or-null#9]
There's variety of packs out there in the wild that have inconsistent metadata like in the case below that comes from `Bangers Only`'s `Ballin'`, where `#MUSIC` states a name for a song file that doesn't exist:

![image](https://github.com/telperion/nine-or-null/assets/9034451/07299cb4-97de-464d-ab3e-b5ded791bc19)

Technically `nine-or-null` does exactly what it's told to do, but it fails silently, while the game plays such simfiles correctly. The biggest issue is that one can miss a song when they run `nine-or-null` for the whole pack because there's no indication in the UI that something has failed and the list will be partially filled.

Full log in text form for better indexing:
```
[2023-08-08 18:21:08.034] INFO     ====================   +9ms or Null? v0.8.0 (GUI)   ====================
[2023-08-08 18:21:08.034] INFO     Parameter settings:
[2023-08-08 18:21:08.035] INFO     	root_path = Z:\games\stepmania\Songs\Bangers Only\Ballin_
[2023-08-08 18:21:08.035] INFO     	report_path = Z:\games\stepmania\Songs\Bangers Only\Ballin_\__bias-check
[2023-08-08 18:21:08.035] INFO     	consider_null = True
[2023-08-08 18:21:08.035] INFO     	consider_p9ms = True
[2023-08-08 18:21:08.035] INFO     	tolerance = 4.0
[2023-08-08 18:21:08.035] INFO     	confidence_limit = 0.8
[2023-08-08 18:21:08.035] INFO     	fingerprint_ms = 50
[2023-08-08 18:21:08.035] INFO     	window_ms = 10
[2023-08-08 18:21:08.035] INFO     	step_ms = 0.2
[2023-08-08 18:21:08.036] INFO     	kernel_target = 0
[2023-08-08 18:21:08.036] INFO     	kernel_type = 0
[2023-08-08 18:21:08.036] INFO     	magic_offset = 0.0
[2023-08-08 18:21:08.036] INFO     Found 1 simfiles in Z:\games\stepmania\Songs\Bangers Only\Ballin_
[2023-08-08 18:21:08.036] INFO     	.
[2023-08-08 18:21:08.037] INFO     (1/1: 00:00:00 elapsed)
[2023-08-08 18:21:08.040] ERROR    [Errno 2] No such file or directory: "Z:\\games\\stepmania\\Songs\\Bangers Only\\Ballin_\\Ballin'.ogg"
Traceback (most recent call last):
  File "nine_or_null\__init__.py", line 738, in batch_process
  File "nine_or_null\__init__.py", line 372, in check_sync_bias
  File "pydub\audio_segment.py", line 651, in from_file
  File "pydub\utils.py", line 60, in _fd_or_path_or_tempfile
FileNotFoundError: [Errno 2] No such file or directory: "Z:\\games\\stepmania\\Songs\\Bangers Only\\Ballin_\\Ballin'.ogg"
[2023-08-08 18:21:08.041] INFO     ------------------------------------------------------------------------
[2023-08-08 18:21:08.041] INFO     Sync bias report: 0 fingerprints processed in Z:\games\stepmania\Songs\Bangers Only\Ballin_
[2023-08-08 18:21:08.041] INFO     Charts sync'd to +9ms: 0
[2023-08-08 18:21:08.041] INFO     Charts sync'd to null: 0
[2023-08-08 18:21:08.042] INFO     Charts sync'd to ????: 0
[2023-08-08 18:21:08.042] INFO     ========================================================================
[2023-08-08 18:21:08.042] INFO     Pack sync paradigm: ????
[2023-08-08 18:21:08.042] INFO     ------------------------------------------------------------------------
```

**Comment by telperion** [comment]
good call - I would like nine-or-null to have the same default as stepmania (although it's a little frustrating that a simfile can be made without explicitly pointing to the music).
